Window.SetBackgroundTopColor(0.012, 0.008, 0.055);
Window.SetBackgroundBottomColor(0.070, 0.018, 0.150);

logo.image = Image("lumina-logo.png");
logo.sprite = Sprite(logo.image);
logo.sprite.SetX(Window.GetWidth() / 2 - logo.image.GetWidth() / 2);
logo.sprite.SetY(Window.GetHeight() / 2 - logo.image.GetHeight() / 2);

fun display_message_callback(text) {
    message.image = Image.Text(text, 1, 1, 1);
    message.sprite = Sprite(message.image);
    message.sprite.SetX(Window.GetWidth() / 2 - message.image.GetWidth() / 2);
    message.sprite.SetY(Window.GetHeight() * 0.78);
}

Plymouth.SetDisplayMessageFunction(display_message_callback);
