PACKAGE_NAME="brcmfmac-ap6611"
PACKAGE_VERSION="7.1.12"
AUTOINSTALL="yes"

BUILT_MODULE_NAME[0]="brcmfmac"
BUILT_MODULE_LOCATION[0]="output"
DEST_MODULE_LOCATION[0]="/extra"

MAKE[0]="make KERNELRELEASE=${kernelver} KERNEL_SOURCE=${kernel_source_dir}"
BUILD_EXCLUSIVE_ARCH="aarch64"
BUILD_EXCLUSIVE_CONFIG="CONFIG_BRCMFMAC"
BUILD_EXCLUSIVE_KERNEL="^7\\.1\\."
