# =========================================================================
# Lumina Linux Universal Boot Script
# =========================================================================
# Do not edit this file directly. Edit /boot/luminaEnv.txt instead.
# Recompile with: mkimage -C none -A arm -T script -d boot.cmd boot.scr
# =========================================================================

setenv load_addr "0x09000000"
setenv overlay_error "false"

test -n "${distro_bootpart}" || distro_bootpart=1

# -------------------------------------------------------------------------
# 1. LOAD ENVIRONMENT OVERRIDES FIRST
# -------------------------------------------------------------------------
if test -e ${devtype} ${devnum}:${distro_bootpart} ${prefix}luminaEnv.txt; then
    echo "-> Loading /boot/luminaEnv.txt"
    load ${devtype} ${devnum}:${distro_bootpart} ${load_addr} ${prefix}luminaEnv.txt
    env import -t ${load_addr} ${filesize}
else
    echo "-> WARNING: luminaEnv.txt not found."
fi

# -------------------------------------------------------------------------
# 2. DEFAULT CONFIGURATION (If not provided by luminaEnv)
# -------------------------------------------------------------------------
test -n "${rootdev}" || setenv rootdev "/dev/mmcblk0p2"
test -n "${verbosity}" || setenv verbosity "1"
test -n "${console}" || setenv console "both"
test -n "${bootlogo}" || setenv bootlogo "true"
test -n "${rootfstype}" || setenv rootfstype "ext4"
test -n "${earlycon}" || setenv earlycon "off"

echo "====================================================="
echo " Lumina Bootloader Initializing..."
echo " Booting from : ${devtype} ${devnum}:${distro_bootpart}"
echo " Target Root  : ${rootdev}"
echo "====================================================="

# -------------------------------------------------------------------------
# 3. CONSTRUCT BOOT ARGUMENTS
# -------------------------------------------------------------------------
if test "${logo}" = "disabled"; then setenv logo "logo.nologo"; fi

if test "${console}" = "display" || test "${console}" = "both"; then setenv consoleargs "console=tty1"; fi
if test "${console}" = "serial" || test "${console}" = "both"; then setenv consoleargs "console=ttyS2,1500000 ${consoleargs}"; fi
if test "${earlycon}" = "on"; then setenv consoleargs "earlycon ${consoleargs}"; fi

if test "${bootlogo}" = "true"; then
    setenv consoleargs "splash plymouth.ignore-serial-consoles ${consoleargs}"
else
    setenv consoleargs "splash=verbose ${consoleargs}"
fi

# Try to get boot partition UUID safely (Fails gracefully on old U-Boot)
part uuid ${devtype} ${devnum}:${distro_bootpart} boot_partuuid
    
setenv bootargs "root=${rootdev} rootwait rootfstype=${rootfstype} ${consoleargs} consoleblank=0 loglevel=${verbosity} ubootpart=${boot_partuuid} usb-storage.quirks=${usbstoragequirks} ${extraargs} ${extraboardargs}"

if test "${docker_optimizations}" = "on"; then setenv bootargs "${bootargs} cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory"; fi

# -------------------------------------------------------------------------
# 4. LOAD LINUX BINARIES
# -------------------------------------------------------------------------
echo "-> Loading Initrd (uInitrd)..."
load ${devtype} ${devnum}:${distro_bootpart} ${ramdisk_addr_r} ${prefix}uInitrd

echo "-> Loading Kernel (Image)..."
load ${devtype} ${devnum}:${distro_bootpart} ${kernel_addr_r} ${prefix}Image

echo "-> Loading Device Tree (${fdtfile})..."
load ${devtype} ${devnum}:${distro_bootpart} ${fdt_addr_r} ${prefix}dtb/${fdtfile}

fdt addr ${fdt_addr_r}
fdt resize 65536

# -------------------------------------------------------------------------
# 5. APPLY DEVICETREE OVERLAYS
# -------------------------------------------------------------------------
if test -n "${overlays}"; then
    for overlay_file in ${overlays}; do
        if load ${devtype} ${devnum}:${distro_bootpart} ${load_addr} ${prefix}dtb/rockchip/overlay/${overlay_prefix}-${overlay_file}.dtbo; then
            echo "   + Applying kernel DT overlay: ${overlay_prefix}-${overlay_file}.dtbo"
            fdt apply ${load_addr} || setenv overlay_error "true"
        elif load ${devtype} ${devnum}:${distro_bootpart} ${load_addr} ${prefix}dtb/rockchip/overlay/${overlay_file}.dtbo; then
            echo "   + Applying kernel DT overlay: ${overlay_file}.dtbo"
            fdt apply ${load_addr} || setenv overlay_error "true"
        fi
    done
fi

if test -n "${user_overlays}"; then
    for overlay_file in ${user_overlays}; do
        if load ${devtype} ${devnum}:${distro_bootpart} ${load_addr} ${prefix}overlay-user/${overlay_file}.dtbo; then
            echo "   + Applying user DT overlay: ${overlay_file}.dtbo"
            fdt apply ${load_addr} || setenv overlay_error "true"
        fi
    done
fi

if test "${overlay_error}" = "true"; then
    echo "-> ERROR applying DT overlays! Restoring original DTB."
    load ${devtype} ${devnum}:${distro_bootpart} ${fdt_addr_r} ${prefix}dtb/${fdtfile}
else
    if test -e ${devtype} ${devnum}:${distro_bootpart} ${prefix}dtb/rockchip/overlay/${overlay_prefix}-fixup.scr; then
        load ${devtype} ${devnum}:${distro_bootpart} ${load_addr} ${prefix}dtb/rockchip/overlay/${overlay_prefix}-fixup.scr
        echo "   + Applying DT fixup script: ${overlay_prefix}-fixup.scr"
        source ${load_addr}
    fi
    if test -e ${devtype} ${devnum}:${distro_bootpart} ${prefix}fixup.scr; then
        load ${devtype} ${devnum}:${distro_bootpart} ${load_addr} ${prefix}fixup.scr
        echo "   + Applying user DT fixup script: fixup.scr"
        source ${load_addr}
    fi
fi

# -------------------------------------------------------------------------
# 6. BOOT
# -------------------------------------------------------------------------
echo "-> Booting Lumina Linux..."
booti ${kernel_addr_r} ${ramdisk_addr_r} ${fdt_addr_r}