#!/usr/bin/env python3
"""Generate one desktop-only project manifest per native architecture."""
import argparse
import copy
from graphlib import TopologicalSorter
from pathlib import Path
import yaml

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
root = Path(__file__).resolve().parents[2]
source = yaml.safe_load((root/'.lumina/packages.yaml').read_text())['packages']
desktop = {name: spec for name, spec in source.items()
           if spec['spec'].startswith('desktop/') or name in ['lumina-release', 'lumina-artwork']}
for arch in ['aarch64', 'x86_64']:
    packages = copy.deepcopy(desktop)
    path = f'.lumina/desktop-{arch}.yaml'
    for name, spec in packages.items():
        spec['targets'] = [f'fedora-44-{arch}']
        spec['promotion_group'] = f'cassiopeia-desktop-26.9-{arch}'
        spec['paths'].append(path)
        assert (root/spec['spec']).is_file(), name
        assert all(dep in packages for dep in spec.get('depends_on', [])), name
    assert len({spec['spec'] for spec in packages.values()}) == len(packages)
    list(TopologicalSorter({name: spec.get('depends_on', []) for name, spec in packages.items()}).static_order())
    output = '# Generated by desktop/tools/desktop-manifests.py; one target per CI binding.\n'
    output += yaml.safe_dump({'version': 1, 'packages': packages}, sort_keys=False, width=100)
    if args.check:
        if (root/path).read_text() != output:
            raise SystemExit(f'{path} is stale; regenerate desktop manifests')
    else:
        (root/path).write_text(output)
    print(f'{path}: {len(packages)} packages, single-target bindings, acyclic dependencies')
