#!/usr/bin/env python3
"""Generate one desktop-only project manifest per native architecture."""
import argparse
import copy
import subprocess
from graphlib import TopologicalSorter
from pathlib import Path
import yaml

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
root = Path(__file__).resolve().parents[2]
desktop = yaml.safe_load((root/'.lumina/desktop-packages.yaml').read_text())['packages']
for arch in ['aarch64', 'x86_64']:
    packages = copy.deepcopy(desktop)
    # Publish architecture-independent RPMs once. LuminaCI rejects a second
    # candidate with the same noarch NEVRA in the shared repository.
    if arch == 'x86_64':
        packages = {
            name: spec for name, spec in packages.items()
            if subprocess.check_output(
                ['rpmspec', '--target', arch, '-q', '--qf', '%{ARCH}\n', str(root/spec['spec'])],
                text=True).splitlines()[0] != 'noarch'
        }
        for spec in packages.values():
            if 'depends_on' in spec:
                spec['depends_on'] = [dep for dep in spec['depends_on'] if dep in packages]
    path = f'.lumina/desktop-{arch}.yaml'
    for name, spec in packages.items():
        spec['targets'] = [f'fedora-44-{arch}']
        spec['promotion_group'] = f'cassiopeia-desktop-26.9-{arch}'
        spec['paths'].extend([path, '.lumina/desktop-packages.yaml', 'desktop/tools/desktop-manifests.py'])
        assert (root/spec['spec']).is_file(), name
        assert all(dep in packages for dep in spec.get('depends_on', [])), name
    assert len({spec['spec'] for spec in packages.values()}) == len(packages)
    list(TopologicalSorter({name: spec.get('depends_on', []) for name, spec in packages.items()}).static_order())
    output = '# Generated by desktop/tools/desktop-manifests.py; one target per CI binding.\n'
    output += yaml.safe_dump({'version': 1, 'packages': packages}, sort_keys=False, width=100)
    if args.check:
        if (root/path).read_text() != output:
            raise SystemExit(f'{path} is stale; regenerate desktop manifests')
    else:
        (root/path).write_text(output)
    print(f'{path}: {len(packages)} packages, single-target bindings, acyclic dependencies')
