# Anaconda configuration for the 1T Lumina Jetson installer.

[Profile]
profile_id = lumina
base_profile = fedora

[Profile Detection]
os_id = lumina

[Network]
default_on_boot = FIRST_WIRED_WITH_LINK

[Bootloader]
efi_dir = lumina

[Storage]
default_scheme = PLAIN

[Payload]
default_source = CLOSEST_MIRROR

[User Interface]
custom_stylesheet = /usr/share/anaconda/pixmaps/lumina.css
